<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>scopeName</key>
	<string>source.pocket-builder</string>
	<key>fileTypes</key>
	<array>
		<string>builder</string>
	</array>
	<key>name</key>
	<string>pocket-builder</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>comment.line</string>
			<key>match</key>
			<string>#.*$</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type</string>
			<key>match</key>
			<string>@".*?(?&lt;![^\\][\\])"</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric</string>
			<key>match</key>
			<string>=[0-9]*&gt;\s*".*?(?&lt;![^\\][\\])"</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function</string>
			<key>match</key>
			<string>=[0-9]*&gt;\s*(&amp;|@)".*?(?&lt;![^\\][\\])"</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted</string>
			<key>match</key>
			<string>(".*?(?&lt;![^\\][\\])"|null)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control</string>
			<key>match</key>
			<string>^\s*:\s*(tag|version|author|time|desc|flag|verify)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type</string>
			<key>match</key>
			<string>@(null|index|string|text|u8|s8|u16|s16|u32|s32|u64|s64|f16|f32|f64|f128|largeN|"[^\s]*")\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter</string>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted</string>
					<key>match</key>
					<string>".*?(?&lt;![^\\][\\])"</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function</string>
			<key>begin</key>
			<string>=[0-9]*&gt;\s*\(\s*(u8|s8|u16|s16|u32|s32|u64|s64|f32|f64)\s*(\[\s*[0-9a-fx]*\s*\])?\)\s*\{</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.float</string>
					<key>match</key>
					<string>(?&lt;!\w)(?i)0[DFT][+-]?(\d+(\.\d*)|\.\d+)(e[+-]?[0-9]+)?</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w)[-+~]?(?i)(0x)[A-F0-9]+\b</string>
					<key>name</key>
					<string>constant.numeric.hex</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w)[-+~]?(\d+(\.\d*)?|\.\d+)(e[+-]?[0-9]+)?(?=[-\s,;&lt;&gt;/+~$%()]|$)</string>
					<key>name</key>
					<string>constant.numeric.decimal</string>
				</dict>
			</array>
		</dict>
	</array>
</dict>
</plist>
